name: DevSecOps CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devsecops-tp-app .

      - name: Scan vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-tp-app

      - name: Install dependencies
        run: |
          npm install

      - name: Run automated tests
        run: npm test  
